export const AuthActions = {
    AUTH_REGISTER: "AUTH_REGISTER",
    AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS", 
    AUTH_REGISTER_ERROR: "AUTH_REGISTER_ERROR",
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS", 
    AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
    AUTH_LOGOUT: "AUTH_LOGOUT"
}