export const CartActions = {
    APPEND_ITEM_CART: "APPEND_ITEM_CART",
    REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
    DECREASE_ITEM_CART: "DECREASE_ITEM_CART",
    CLEAR_ITEM_CART: "CLEAR_ITEM_CART"

}